[2025-10-03T14:40:58.143+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T14:40:58.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T14:40:58.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T14:40:58.187+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T14:40:58.208+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-02 00:00:00+00:00
[2025-10-03T14:40:58.218+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T14:40:58.224+0000] {standard_task_runner.py:64} INFO - Started process 1310 to run task
[2025-10-03T14:40:58.222+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/test_ml_dag.py', '--cfg-path', '/tmp/tmp00kmo8ah']
[2025-10-03T14:40:58.230+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask dbt_deps
[2025-10-03T14:40:58.401+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [running]> on host 68ec1039cc61
[2025-10-03T14:40:58.656+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T14:40:58.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T14:40:58.667+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T14:40:58.670+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-10-03T14:40:58.695+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T14:40:58.701+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/dbt: No such file or directory
[2025-10-03T14:40:58.702+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-03T14:40:58.704+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T14:40:58.726+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-03T14:40:58.735+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T144058, end_date=20251003T144058
[2025-10-03T14:40:58.779+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 1.; 1310)
[2025-10-03T14:40:58.806+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-03T14:40:58.844+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T14:40:58.849+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-03T15:12:59.349+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T15:12:59.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:12:59.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:12:59.428+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T15:12:59.459+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-02 00:00:00+00:00
[2025-10-03T15:12:59.473+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T15:12:59.476+0000] {standard_task_runner.py:64} INFO - Started process 126 to run task
[2025-10-03T15:12:59.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpw71e7tsv']
[2025-10-03T15:12:59.485+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask dbt_deps
[2025-10-03T15:12:59.607+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [running]> on host a73834a871b4
[2025-10-03T15:12:59.753+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T15:12:59.756+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T15:12:59.764+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T15:12:59.767+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR=/opt/***/dbt dbt deps']
[2025-10-03T15:12:59.789+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T15:12:59.822+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-10-03T15:12:59.824+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-03T15:12:59.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T15:12:59.844+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-03T15:12:59.857+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T151259, end_date=20251003T151259
[2025-10-03T15:12:59.889+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 127.; 126)
[2025-10-03T15:12:59.935+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-03T15:12:59.973+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T15:12:59.979+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-03T15:26:39.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T15:26:39.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:26:39.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:26:39.904+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T15:26:39.928+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-02 00:00:00+00:00
[2025-10-03T15:26:39.949+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T15:26:39.956+0000] {standard_task_runner.py:64} INFO - Started process 127 to run task
[2025-10-03T15:26:39.953+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpq0keqpjh']
[2025-10-03T15:26:39.960+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask dbt_deps
[2025-10-03T15:26:40.115+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [running]> on host 050f8c50766f
[2025-10-03T15:26:40.324+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T15:26:40.327+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T15:26:40.330+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T15:26:40.333+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR=/opt/***/dbt dbt deps']
[2025-10-03T15:26:40.363+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T15:26:40.370+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-10-03T15:26:40.371+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-03T15:26:40.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T15:26:40.396+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-03T15:26:40.406+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T152639, end_date=20251003T152640
[2025-10-03T15:26:40.441+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 127.; 127)
[2025-10-03T15:26:40.496+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-03T15:26:40.557+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T15:26:40.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-03T15:52:13.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T15:52:13.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:52:13.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T15:52:13.742+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T15:52:13.764+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-02 00:00:00+00:00
[2025-10-03T15:52:13.775+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T15:52:13.777+0000] {standard_task_runner.py:64} INFO - Started process 255 to run task
[2025-10-03T15:52:13.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp9_rzba9u']
[2025-10-03T15:52:13.781+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask dbt_deps
[2025-10-03T15:52:13.877+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [running]> on host 88331542f089
[2025-10-03T15:52:14.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T15:52:14.026+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T15:52:14.029+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T15:52:14.031+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR=/opt/***/dbt dbt deps']
[2025-10-03T15:52:14.054+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T15:52:19.149+0000] {subprocess.py:93} INFO - [0m15:52:19  Running with dbt=1.10.13
[2025-10-03T15:52:19.410+0000] {subprocess.py:93} INFO - [0m15:52:19  Warning: No packages were found in packages.yml
[2025-10-03T15:52:19.421+0000] {subprocess.py:93} INFO - [0m15:52:19  Warning: No packages were found in packages.yml
[2025-10-03T15:52:20.262+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-03T15:52:20.270+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T15:52:20.345+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T155213, end_date=20251003T155220
[2025-10-03T15:52:20.410+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-03T15:52:20.452+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-03T15:52:20.458+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-10-03T16:16:37.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T16:16:37.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T16:16:37.777+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T16:16:37.777+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T16:16:37.792+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-02 00:00:00+00:00
[2025-10-03T16:16:37.806+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=627) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T16:16:37.808+0000] {standard_task_runner.py:64} INFO - Started process 629 to run task
[2025-10-03T16:16:37.808+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/test_ml_dag.py', '--cfg-path', '/tmp/tmpyoy81y4u']
[2025-10-03T16:16:37.812+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask dbt_deps
[2025-10-03T16:16:37.890+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2025-10-02T00:00:00+00:00 [running]> on host 88331542f089
[2025-10-03T16:16:38.012+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T16:16:38.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T16:16:38.018+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T16:16:38.020+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-10-03T16:16:38.043+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T16:16:43.844+0000] {subprocess.py:93} INFO - [0m16:16:43  Running with dbt=1.10.13
[2025-10-03T16:16:44.504+0000] {subprocess.py:93} INFO - [0m16:16:44  Warning: No packages were found in packages.yml
[2025-10-03T16:16:44.521+0000] {subprocess.py:93} INFO - [0m16:16:44  Warning: No packages were found in packages.yml
[2025-10-03T16:16:45.789+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-03T16:16:45.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T16:16:45.864+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T161637, end_date=20251003T161645
[2025-10-03T16:16:45.915+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-03T16:16:45.958+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-03T16:16:45.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
