[2025-10-03T14:34:56.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T14:34:56.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2025-10-03T14:34:56.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2025-10-03T14:34:56.426+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-03T14:34:56.447+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2022-03-01 00:00:00+00:00
[2025-10-03T14:34:56.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T14:34:56.491+0000] {standard_task_runner.py:64} INFO - Started process 1220 to run task
[2025-10-03T14:34:56.487+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2022-03-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp0pc_xbj2']
[2025-10-03T14:34:56.493+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask dbt_deps
[2025-10-03T14:34:56.575+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [running]> on host 68ec1039cc61
[2025-10-03T14:34:56.709+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2022-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-01T00:00:00+00:00'
[2025-10-03T14:34:56.712+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T14:34:56.714+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T14:34:56.727+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-10-03T14:34:56.752+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T14:34:56.780+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/dbt: No such file or directory
[2025-10-03T14:34:56.781+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-03T14:34:56.784+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T14:34:56.799+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-03T14:34:56.809+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2022-03-01T00:00:00+00:00, execution_date=20220301T000000, start_date=20251003T143456, end_date=20251003T143456
[2025-10-03T14:34:56.831+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 1.; 1220)
[2025-10-03T14:34:56.869+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-03T14:34:56.903+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T14:34:56.913+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
