[2025-10-03T14:26:00.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T14:26:00.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2025-10-03T14:26:00.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2025-10-03T14:26:00.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T14:26:00.502+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2022-03-01 00:00:00+00:00
[2025-10-03T14:26:00.512+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T14:26:00.515+0000] {standard_task_runner.py:64} INFO - Started process 1110 to run task
[2025-10-03T14:26:00.514+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'scheduled__2022-03-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_ml_dag.py', '--cfg-path', '/tmp/tmpcc7pk4sv']
[2025-10-03T14:26:00.518+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask dbt_deps
[2025-10-03T14:26:00.583+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps scheduled__2022-03-01T00:00:00+00:00 [running]> on host 68ec1039cc61
[2025-10-03T14:26:00.861+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2022-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-01T00:00:00+00:00'
[2025-10-03T14:26:00.864+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T14:26:00.869+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T14:26:00.870+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-10-03T14:26:00.985+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T14:26:01.025+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/dbt: No such file or directory
[2025-10-03T14:26:01.026+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-03T14:26:01.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T14:26:01.040+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-03T14:26:01.050+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_deps, run_id=scheduled__2022-03-01T00:00:00+00:00, execution_date=20220301T000000, start_date=20251003T142600, end_date=20251003T142601
[2025-10-03T14:26:01.071+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 1.; 1110)
[2025-10-03T14:26:01.097+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-03T14:26:01.124+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-03T14:26:01.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
